repository:
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: PR_BODY
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      required_status_checks: null
      enforce_admins: false
      block_creations: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
        require_last_push_approval: true
        dismiss_stale_reviews: true
      restrictions:
        apps: []
        users: []
        teams: []
